### ISSUE TITLE
如何显示自定义的数据类

### ISSUE THREAD

**Issue by dingxiaowei** [CodeGize/UnityTable#1]
例如:
public class Animal
{
  public int ID{get;set;}
  public string Name{get;set;}
}
我看案例中的数据都是继承自Monobehavior的，然后用的UnityEngine.Object的SerializedProperty

**Comment by CodeGize** [comment]
这个控件是官方代码中用于批量展示Unity对象的Table控件，不支持自定义的数据
如果你要使用自定义的数据，请使用TreeView控件，它和这个控件和类似，只是没有很多自动化的功能。比如下图是我改的ResourceChecker的界面

![截图_20190625120515](https://user-images.githubusercontent.com/9925061/60068533-c0832780-9741-11e9-954f-0a5d1959ce8f.png)

**Comment by CodeGize** [comment]
目前已经做了扩展，可以使用CommonTable,请参考ExampleDataTableWnd.cs

**Comment by CodeGize** [comment]
目前已经做了扩展，可以使用CommonTable,请参考ExampleDataTableWnd.cs
